version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - A-dependency
  - I-dependency-gardening
  versioning-strategy: increase
