on: issue_comment
name: assign_review_by_comment by issue_comment
jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: assign_review_by_comment
      uses: cats-oss/github-action-auto-assign@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
